config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :users, only: [:new, :create]

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  root 'sessions#new'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Album
      cannot :destroy, Album
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  validates :artist, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[show edit update destroy]
  load_and_authorize_resource

  def index
    @albums = Album.all
  end

  def show; end

  def new
    @album = Album.new
  end

  def edit; end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to @album, notice: 'Album was successfully created.'
    else
      render :new
    end
  end

  def update
    if @album.update(album_params)
      redirect_to @album, notice: 'Album was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @album.destroy
    redirect_to albums_url, notice: 'Album was successfully destroyed.'
  end

  private

  def set_album
    @album = Album.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:artist, :album, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to root_path, alert: 'You must be logged in to access this page.' if current_user.nil?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authorize, except: %i[new create]

  def new; end

  def create
    if user&.authenticate(params[:login][:password])
      session[:user_id] = user.id.to_s
      redirect_to albums_path, notice: 'Successfully logged in!'
    else
      flash.now.alert = "Sorry, we couldn't find an account with this username."\
                         " Please check you're using the right username and try again."
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path, notice: 'Logged out!'
  end

  private

  def user
    @user ||= User.find_by(username: params[:login][:username])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:fullname, :username, :password, :password_confirmation, :role)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def artists_select
    artists = ::Albums::ListArtists.call
    artists.map { |_key, value| [value['name']] }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    flash.each do |msg_type, message|
      concat(tag.div(message, class: "alert #{bootstrap_class_for(msg_type)}", role: 'alert') do
               concat tag.button('x', class: 'close', data: { dismiss: 'alert' })
               concat message
             end)
    end
    nil
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<%= form_with(model: album, local: true) do |form| %>
  <% if album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :artist %>
    <%= form.select :artist, artists_select , {}, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :album %>
    <%= form.text_field :album, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :year %>
    <%= form.text_field :year, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
    <%= link_to 'Back', albums_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form', album: @album %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<h1>Albums</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Artist</th>
      <th scope="col">Album</th>
      <th scope="col">Year</th>
      <th colspan="6"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each_with_index do |album, index| %>
      <tr>
        <th scope="row"><%= index + 1%></th>
        <td><%= album.artist %></td>
        <td><%= album.album %></td>
        <td><%= album.year %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <% if can? :destroy, Album %>
          <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form', album: @album %>

app/views/albums/show.html.erb
<p>
  <strong>Artist:</strong>
  <%= @album.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @album.album %>
</p>

<p>
  <strong>Year:</strong>
  <%= @album.year %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <%= flash_messages %>

      <% if current_user %>
	    <%= "Logged in as #{current_user.username}" %> | <%= link_to 'Log Out', logout_path, method: :delete %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :fullname %>
    <%= form.text_field :fullname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :role %>
    <%= form.select :role, ['admin', 'user'], {}, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary'%>
    <%= link_to 'Back', users_path, class: 'btn btn-link' %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>